// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizationX.Data;

namespace OrganizationX.Migrations.Employee
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrganizationX.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Age")
                        .HasColumnType("bigint");

                    b.Property<string>("Attrition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessTravel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DailyRate")
                        .HasColumnType("bigint");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DistanceFromHome")
                        .HasColumnType("bigint");

                    b.Property<long>("Education")
                        .HasColumnType("bigint");

                    b.Property<string>("EducationField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmployeeCount")
                        .HasColumnType("bigint");

                    b.Property<long>("EnvironmentSatisfaction")
                        .HasColumnType("bigint");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HourlyRate")
                        .HasColumnType("bigint");

                    b.Property<long>("JobInvolvement")
                        .HasColumnType("bigint");

                    b.Property<long>("JobLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("JobSatisfaction")
                        .HasColumnType("bigint");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MonthlyIncome")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlyRate")
                        .HasColumnType("bigint");

                    b.Property<long>("NumCompaniesWorked")
                        .HasColumnType("bigint");

                    b.Property<string>("Over18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PercentSalaryHike")
                        .HasColumnType("bigint");

                    b.Property<long>("PerformanceRating")
                        .HasColumnType("bigint");

                    b.Property<long>("RelationshipSatisfaction")
                        .HasColumnType("bigint");

                    b.Property<long>("StandardHours")
                        .HasColumnType("bigint");

                    b.Property<long>("StockOptionLevel")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalWorkingYears")
                        .HasColumnType("bigint");

                    b.Property<long>("TrainingTimesLastYear")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkLifeBalance")
                        .HasColumnType("bigint");

                    b.Property<long>("YearsAtCompany")
                        .HasColumnType("bigint");

                    b.Property<long>("YearsInCurrentRole")
                        .HasColumnType("bigint");

                    b.Property<long>("YearsSinceLastPromotion")
                        .HasColumnType("bigint");

                    b.Property<long>("YearsWithCurrManager")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeNumber");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
